# Based on:-
# * https://github.com/peaceiris/actions-gh-pages
on:
  push:
     branches:
       - master

name: Render documentation

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: _build/html/
