# Based on:-
# * https://github.com/peaceiris/actions-gh-pages
on:
  push:
     branches:
       - master

name: Render documentation

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

#      - name: Install dependencies
#        run: "sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "."

      - name: Disable Jekyll
        run: "touch ${{GITHUB_WORKSPACE}}/_build/html/.nojekyll"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: _build/html/
